### ISSUE TITLE
Save Context Fail

### ISSUE THREAD

**Issue by matbenitez** [Superalgos/CloneExecutor#10]
A network connection reset issue on the  Blob Storage:
[ERROR] createTextFile -> onFileCreated -> err = {"code":"ECONNRESET","errno":"ECONNRESET","syscall":"read"}

Cause the Context to fail when saving the execution result:
[ERROR] saveThemAll -> onDone -> Retry Later. Requesting Execution Retry.

This will trigger a retry,  and the Trading Boot Process Main Loop will fail with message:
[ERROR] run -> loop -> saveContext -> onFinished > Can not retry at this point.

Need to check this scenario to allow the process to retry the blob action a certain number of times, since there is no dependencies and the execution of the bot was sucessful.

**Comment by Luis-Fernando-Molina** [comment]
thanks will check it

**Comment by Luis-Fernando-Molina** [comment]
Shall we close this issue @matbenitez ?
